# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


author: Mohamed BEN HAMDOUNE
title: Artificial Mind Blog.
subtitle: Yet Another Artificial Intelligence Blog.

email: mbenhamd@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my website, it includes a part about my career, 
  but there are articles about my projects and some about 
  new concepts in the field of artificial intelligence.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.artificialmind.io"
twitter_username: mbenhamdtw
github_username:  mbenhamd
linkedin_username: mohamed-ben-hamdoune-73197392
twitter_url: https://twitter.com/mbenhamdtw
linkedin_url: https://www.linkedin.com/in/mohamed-ben-hamdoune-73197392/
github_url: https://github.com/mbenhamd

avatar: assets/images/avatar.jpg

# Google Analytics Tracking ID goes here:
google_analytics: UA-126712513-1

# Build settings
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
#theme: jekyll-theme-prologue
gfm_quirks: paragraph_end
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: Curriculum Vitae
    url: /curriculum-vitae/
  - text: Archive
    url: /tags/
  - text: About
    url: /about/      
  

# The shortname for your Disqus site to enable comments.
disqus: justgoodthemes

# Colors
accent_color: '#2c343c'

# Site footer
footer:
  content: "Artificial Mind Blog. Jekyll Theme Forked [Here](https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme)."
  has_social: true

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page/:num'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed


jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

enabled: all
enabled:
  - categories
enabled:
  - year
  - month
  - tags

#layout: archive                  # _layouts/archive.html

layouts:
  year: year-archive
  month: month-archive
  day: day-archive
  tag: tag-archive-layout

# Footer
footer_show_references: false

collections: [sections]          
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  I was born in France and did my schooling in France. I am fluent in English and French as well as Arabic. <br/>
  After a bachelor's degree in mathematics and computer science I specialized with a master's degree in artificial intelligence. The learning axes are mainly carried out on these axes.
  - Clustering 
  - Supervised learning (Classication / Regression)
  - Visualization
  - Reinforcement learning

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/images/avatar.jpg
about_content: | # this will include new lines to allow paragraphs    
  I am currently looking for work after completing my research internship in a public laboratory. This internship allowed me to learn many things in the field of research and taught me how to ask a methodology and write about scientific research.
  Here is an exhaustive list of tools that I use daily. <br/>
  Software Development / Cloud :
    - Python, C, C++, R, Java
    - Scikit-Learn
    - Tensorfow / Keras
    - Apache Spark / Hadoop
    - Elasticsearch
    - AWS (Amazon Web Service)
    - Microsoft Azure
    - GCP (Google Cloud Computing)
    - Angular, React, API RESTful

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

